### ISSUE TITLE
Critical-CH web-platform elements

### ISSUE THREAD

**Issue by amtunlimited** [WICG/client-hints-infrastructure#102]
There are elements of the Critical-CH restart mechanism (from the client hints reliability explainer and [HTTP experimental draft](https://www.ietf.org/archive/id/draft-davidben-http-client-hint-reliability-03.html#name-the-critical-ch-response-he) that would fit better in web-platform land than in HTTP land (similar to this draft vs RFC8942). @davidben has mentioned this before in davidben/http-client-hint-reliability#4, and the issues mentioned have since been resolved.

Does it make sense to start specifying the web-platform components of Critical-CH? More importantly, should that be an addition to this draft or a new draft that is dependent on this one?

**Comment by davidben** [comment]
Web platform things typically aren't specified in IETF drafts. I think the right place to capture those would be this repository, and eventually Fetch itself.

**Comment by arichiv** [comment]
Just to be sure, the idea is to extend this draft to contain the Critical-CH header? If so, it seems like that would require an update to Section 2 and possibly a new section dedicated to outlining how the header interacts with everything else.
