### ISSUE TITLE
Readme explainer still says `Accept-CH` but spec changed to `Delegate-CH`

### ISSUE THREAD

**Issue by summercms** [WICG/client-hints-infrastructure#111]
Hi,

The following pull request code change found here: https://github.com/WICG/client-hints-infrastructure/pull/109/files

Changes `Accept-CH` into `Delegate-CH`, however when I go to the `readme.md` of this repo it's not been updated.

See here: https://github.com/WICG/client-hints-infrastructure#accept-ch

Maybe this part needs updating as well?

@arichiv

**Comment by miketaylr** [comment]
`Accept-CH` the header hasn't been renamed, instead the `delegate-ch` token when used via `<meta>` has been added (or I guess `accept-ch` renamed in this specific context, technically). We should update explainer to make that clear and cover the markup-based scenario in particular.
