### ISSUE TITLE
Consider a new class of low-entropy CHs that a subresource can request

### ISSUE THREAD

**Issue by miketaylr** [WICG/client-hints-infrastructure#142]
See the discussion at https://github.com/WICG/attribution-reporting-api/issues/552#issuecomment-1416171051

> I agree that defining this is a low-entropy CH would add passive fingerprinting data in non-ideal ways.
>
> I need to think about this some more, but it seems to me that this proposal is trying to reinvent Client Hints because Client Hints cannot be opted in from a subresource response. The reason for that restriction is that we didn't want to provide passive resources access to data that they didn't already had (as they don't have access to JS APIs).
>
> At the same time, maybe there's room to reconsider that historical decision for low-entropy hints. Maybe we could define a new class of low-entropy hints that can be opted-in from subresources.

**Comment by arichiv** [comment]
I proposed having this be a permissions policy + link attribute rather than also adding a client hint. Given the top-frame doesn't need the information on first-request this seems to make more sense.
