### ISSUE TITLE
Bug in spec, subresources don't get client hints as a result

### ISSUE THREAD

**Issue by jkarlin** [WICG/client-hints-infrastructure#151]
Section 6 of the spec (for fetch) says to run the algorithm in section 5 (navigation requests). But section 5 won't add a hint if the request is not a navigation request. As a result, according to the spec, subresource requests (fetch) shouldn't get client hints.

**Comment by arichiv** [comment]
I think step 6 is actually correct as written, it doesn't block unless the request is both not a navigation request and the current permissions policy doesn't allow. I can fix the wording to be clearer though.
