### ISSUE TITLE
Is Delegate-CH a pragma or not?

### ISSUE THREAD

**Issue by eeeps** [WICG/client-hints-infrastructure#159]
Chrome currently only supports:

```
<meta http-equiv="Delegate-CH">
```

but if I'm reading the spec correctly (step three of [the Delegate-CH algorithm](https://wicg.github.io/client-hints-infrastructure/#delegate-ch-algo)), it seems to call for:

```
<meta name="Delegate-CH">
```

Which is correct?

**Comment by miketaylr** [comment]
Thanks for the issue @eeeps :)

I think given @arichiv's PR, we can conclude that `http-equiv` is the right answer.
