### ISSUE TITLE
Send low-entropy hints on all requests

### ISSUE THREAD

**Issue by yoavweiss** [WICG/client-hints-infrastructure#19]
Current spec says that low-entropy hints are sent without an opt-in only on navigation requests. 

That can have multiple implications:
* First parties have to opt-in in order to get those hints for their subresources.
* Third parties require delegation in order to get those hints.

That seems overly restrictive, and doesn't match current implementation. I think we should change that.

**Comment by amtunlimited** [comment]
Random thought: would it make sense to change the default feature policy for `ua` and `ua-mobile` to `*`?

**Comment by yoavweiss** [comment]
They should be (that's how it's [implemented](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/common/feature_policy/feature_policy.cc;l=406;drc=b13b67fdd3ed8c2f3154e85e9661680d4ce3220e;bpv=1;bpt=1?originalUrl=https:%2F%2Fcs.chromium.org%2F) in Chromium).
