### ISSUE TITLE
Best practice for managing hints throughout multiple requests

### ISSUE THREAD

**Issue by rowan-m** [WICG/client-hints-infrastructure#27]
The `Accept-CH` header acts as a complete replacement for the client hints that the browser should send on subsequent requests. I'm unsure of the right process sites (especially larger site with multiple teams) should follow when managing a selection of hints across the lifetime of the session. This is especially pertinent as the selection of valid hints expands to cover a range of different functionality.

For example:

1. Browser requests `/`
2. Site responds `Accept-CH: DPR, Width, Viewport-Width`
3. Browser sends `DPR`, etc. on subsequent requests which get used for image optimisation
4. Browser requests `/downloads`
5. Site responds with `Accept-CH: UA-Platform`
6. Browser sends `Sec-CH-UA-Platform` which is used to customise download options, but no longer sends `DPR`, etc.

My thoughts for best-practice here is that while the hints are persisted for the session or until a new set is assigned, developers would do better to think of them as specified per navigation. In other words, always send the complete set of hints required for a given page.

Alternatively, use the hint on a given page to set some site controlled variable that can be persisted independently. e.g. a game uses its `/detect-settings` page to examine the `Device-Memory` hint and then sets its own internally managed "quality" preference.

This also allows for advising sending a blank `Accept-CH` header to "reset" state, for example perhaps when a user signs out of a site.

In contrast, I think it would be good to specifically discourage:

- just asking a big static list of all the hints required throughout the site because they're used at some point
- attempting to match incoming request headers to the relevant `Accept-CH` value in order to additively specify another hint

**Comment by arichiv** [comment]
Your suggestions make sense, but I'm not sure this proposal is the right location (since it's focused on the hints requested via HTML markup and never cached). There could be a followup to https://www.rfc-editor.org/rfc/rfc8942#name-security-considerations, but it also seems like best practices might follow more from a privacy budget model, which would encourage more circumspection of the information requested on any given page (per your final two points).
