### ISSUE TITLE
Prefixing of hints or not?

### ISSUE THREAD

**Issue by jonarnes** [WICG/client-hints-infrastructure#28]
The [README.md](https://github.com/WICG/client-hints-infrastructure/blob/master/README.md#example) says:

> If a server's response to a navigation request includes the Accept-CH: foo, bar header, same-origin subresource requests on the page will include the Sec-Foo: foo-value and Sec-Bar: bar-value request headers.

Just looking at how this is implemented in Chrome v85. Seems to treat the "classic" client hints differently than ua-client hints. For `ua-arch` it is indeed prefixed by `sec` but also by by `ch`. The classic hints are not prefixed.

Like usual on the web, implementation trumps specification, but wanted to phrase the question too: Any reason why the "classic" (width, dpr, downlink,ect etc...) hints should be treated differently than the ua-client hints?

**Comment by yoavweiss** [comment]
Apologies for the long delay replying here... :(

There's no particular reason other than backwards-compatibility considerations. We'd need to migrate over existing hint users to a `sec-` prefixed solution, and eventually remove the legacy hints.

**Comment by miketaylr** [comment]
@arichiv is working on this, see https://groups.google.com/a/chromium.org/g/blink-dev/c/wTGpTPtAJGM

**Comment by miketaylr** [comment]
Oops, wrong link: https://github.com/WICG/client-hints-infrastructure/pull/77/files

I think we can close this now.
