### ISSUE TITLE
How do we deal with a Critical-CH hit in the middle of a redirect chain?

### ISSUE THREAD

**Issue by amtunlimited** [WICG/client-hints-infrastructure#33]
What should happen if, for example, the CH requirements change midway through a long redirect chain? The way I see it, there's two options:

1. Restart the request you're currently on, just with the new hints
2. Restart from the beginning of the chain with the new hints

I don't know if there's any precedent to go off of here. 1 seems like the simplest to spec and implement, and is how I would interpret the proposal right now. Number 2 might have useful merits semantically, however. Are there any strong feelings one way or the other?

@davidben, who might have opinions.

**Comment by davidben** [comment]
It should be (1), and that's what the spec already says, by virtue of talking about individual requests. I don't see any benefit of making it (2), only problems with requests getting unexpectedly sent multiple times. What merits were you thinking?

**Comment by amtunlimited** [comment]
>What merits did you have in mind?

After thinking about it a little more thoroughly, I suppose the only actual benefit is if the Critical-CH preferences changed mid-way through a redirect, but that's kind of a long shot.
