### ISSUE TITLE
Client Hint Reliability and DNS SVCB/HTTPSSVC

### ISSUE THREAD

**Issue by rmarx** [WICG/client-hints-infrastructure#35]
Hello all,

I was reading the Reliability draft here and was somewhat surprised to see ALPS listed as an alternative/option, but not the SVCB/HTTPSSVC draft (https://tools.ietf.org/html/draft-ietf-dnsop-svcb-httpssvc-03), nor could I find any mention here on github about DNS-based "solutions" to this problem. It seems there are at least some synergies between client hint reliability and the HTTPSSVC proposal. Has this been discussed elsewhere before maybe? 

As I understand it, SVCB/HTTPSSVC records solve a similar problem in that they allow the client to have server-side information before the first real request on a connection to that server (e.g., proposed use cases are exchanging alt-svc information for QUIC or enforcing HSTS). I am however far from an expert on either client hints nor the DNS proposal, so it could be I'm missing something obvious. Still, I'd expect this alternative to be at least mentioned in the Reliability document, even if it can't/won't be used. 

From my reading of the mailing lists and especially comments from people in the quicwg, it seems there is less enthusiasm for ALPS than there is for HTTPSSVC in the long run from implementers (again, I could be wrong in this). Given that the DNS-based proposal is picking up speed and being implemented/tested by  e.g., Cloudflare and Apple (https://blog.cloudflare.com/speeding-up-https-and-http-3-negotiation-with-dns/), this seems like a good use case to try out as well. 

Looking forward to hearing your thoughts on this!
With best regards,
Robin

**Comment by yoavweiss** [comment]
Hey!

This was discussed at the IETF's HTTPWG (in 106, IIRC) and was met with lukewarn enthusiasm. People mentioned DNS' operational complexity and the distance between that and the content layer, which requires the hints for content negotiation. 
With that said, it might be worthwhile to summarize those points as a "considered alternative".

/cc @davidben

**Comment by davidben** [comment]
I don't think DNS would work here. In addition to the operational complexity Yoav mentioned, SVCB/HTTPSSVC does not meet the security requirements. This would allow a network to inject or manipulate settings in an connection. For Client Hint Reliability in particular, the network would be able to trick the browser into thinking the website is requesting more entropy than it actually is, and potentially trip fingerprinting mitigations. For other such extensions, the impact could be even worse. It is also unlikely to meet performance requirements. DNS over HTTPS is far from universal right now, and classic DNS has ossified to the point that I expect many clients will be unable to fetch the records.

Doing it inline in the connection itself avoids all these issues and has the same performance properties. The TLS 1.3 half-RTT point already early enough.

In terms of ALPS itself, I don't think needing a better way to deal with HTTP/2 SETTINGS and the like is that controversial (there's been exactly such a request from QUIC in https://github.com/quicwg/base-drafts/issues/3086#issuecomment-543373506). Whether it should be done via a TLS extension like ALPS or half-RTT data I think has less consensus. One takeaway from the meeting was I need to write up more clearly what a half-RTT data solution would look like, for comparison. I hope to get that done in the coming weeks.

I think people don't realize how complex and underspecified half-RTT data is, as well as how tight of integration we'd need between the TLS and HTTP layers to get all the ordering right. Despite being a new extension, ALPS is actual the path of lower coupling between the two.

**Comment by rmarx** [comment]
Thanks both for your thorough comments. 

While I agree with @davidben's arguments of course, I still feel it would be useful to have at least a mention of them in the drafts as a "considered alternative". 

I'm looking forward to the half-RTT proposal, as I personally like the ALPS concept and hope concrete use cases like these might give it a bit more momentum.

**Comment by davidben** [comment]
Good idea. I added some text about this in https://github.com/WICG/client-hints-infrastructure/pull/36.
