### ISSUE TITLE
Potential race condition in remove client hints from redirect if needed algorithm

### ISSUE THREAD

**Issue by davidben** [WICG/client-hints-infrastructure#39]
The [remove client hints from redirect if needed](https://wicg.github.io/client-hints-infrastructure/#abstract-opdef-remove-client-hints-from-redirect-if-needed) algorithm uses the request's client's client hint set to determine the headers to remove. If that set has changed since the headers were added, this would miss some cases.

I'm not sure whether the set can change as currently written, but it may end up changing depending on how service worker contexts end up working. Either way, it seems more robust to just loop over all CH headers.

**Comment by arichiv** [comment]
Merging into #48
