### ISSUE TITLE
Handling of child frames

### ISSUE THREAD

**Issue by davidben** [WICG/client-hints-infrastructure#40]
I'm not sure if the frame handling is quite right, if I'm reading the spec correctly:

The algorithm for [initializing the Client Hint set](https://wicg.github.io/client-hints-infrastructure/#document-init) only fills things in on top-level frames. Which I think means that requests within subframes won't pick up any hints in step 1 of [append client hints to request](https://wicg.github.io/client-hints-infrastructure/#abstract-opdef-append-client-hints-to-request).

Additionally, step 2 says the Permissions-Policy check happens on [subresource requests](https://fetch.spec.whatwg.org/#subresource-request), but that doesn't include the subframe navigation itself.

Does it work to say that child documents inherit the top-level document's client hint set? Then we fix the check in step 2 to cover all requests but the top-level navigation? (Or can we just say all of them? I don't know how permissions policy works those requests given the document's still being created.)

**Comment by arichiv** [comment]
Only the top-level document's client hint requests (via HTTP headers or HTML markup) are respected. If the top-level document delegated hints to the origins of sub-frames (or if the sub-frame has the same origin as the top-frame), then they can pick those hints up as well.
