### ISSUE TITLE
Accept-CH cache is not updated on redirects

### ISSUE THREAD

**Issue by davidben** [WICG/client-hints-infrastructure#41]
If, on a top-level navigation, we get a redirect, I believe the spec currently will not pick up Accept-CH on those rounds, since that happens at [create and initialize a Document object](https://html.spec.whatwg.org/multipage/browsing-the-web.html#initialise-the-document-object). (See https://wicg.github.io/client-hints-infrastructure/#document-init and https://wicg.github.io/client-hints-infrastructure/#abstract-opdef-initialize-the-client-hints-set.)

Probably it should happen earlier, maybe in [process a navigate fetch](https://html.spec.whatwg.org/multipage/browsing-the-web.html#process-a-navigate-fetch)?

**Comment by arichiv** [comment]
I'm closing this as intentional, it seems like an abuse of the system to allow redirects to update the Accept-CH cache (instead of using a Critical-CH header). @yoavweiss in case I'm wrong

**Comment by davidben** [comment]
Not sure I follow. Critical-CH depends on the Accept-CH cache in the first place, and there are normal reasons to send redirects. (And, IIRC, our implementation does process Accept-CH on redirect. The problem is the spec doesn't match.)

**Comment by arichiv** [comment]
I was about to follow up that I was wrong, will fix in #42 (since that fix seems to overlap with the need here). Sorry about that
