### ISSUE TITLE
Ensure we align with fetch PR 1000

### ISSUE THREAD

**Issue by miketaylr** [WICG/client-hints-infrastructure#49]
There used to be an Issue block in the spec text, but this issue exists to track the fetch issue on Sec- prefixed headers and CORS safelisting.

https://github.com/WICG/client-hints-infrastructure/pull/47#discussion_r562822919
https://github.com/whatwg/fetch/pull/1000

**Comment by arichiv** [comment]
Closing as resolved since whatwg/fetch#1000 was abandoned
