### ISSUE TITLE
Define interaction between reliability and navigation timing API

### ISSUE THREAD

**Issue by davidben** [WICG/client-hints-infrastructure#58]
Something we should make sure to get right, and also to write down in the spec:

The navigation timing API should reflect any time spent in Critical-CH retries so sites can monitor performance. Certainly `navigationStart` should start before all the retries. From there, given that retries can be interleaved with redirects, I'm thinking we can model these as self-redirect and include them in the `redirectStart` to `redirectEnd` block. Looks like Navigation Timing 2 extends this with a `redirectCount` property, which we'll need to define:
https://www.w3.org/TR/navigation-timing-2/

@yoavweiss, thoughts?

**Comment by yoavweiss** [comment]
Properly defining this makes sense. Ideally, this would fall out of our current effort to integrate NavTiming with Fetch, as the integration of CH-reliability with Fetch.
/cc @noamr
