### ISSUE TITLE
Sec-CH-UA-Full-Version seems to be missing from the spec.

### ISSUE THREAD

**Issue by bat999** [WICG/client-hints-infrastructure#64]
Hi

In Section 7.1 of the spec https://wicg.github.io/client-hints-infrastructure/

It says...
A client hints token is a byte-lowercase representation of one of Save-Data, DPR, Width, Viewport-Width, Viewport-Height, Device-Memory, RTT, Downlink, ECT, Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Model, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version, Sec-CH-UA or Sec-CH-UA-Mobile.

But **Sec-CH-UA-Full-Version** is missing from the list.

Also not mentioned in Section 7.2 or 7.4 either.
Nor in the Section 9 Index.

**Comment by miketaylr** [comment]
Hey @bat999 -- thanks for the issue! I could fix this up real quick, but would you like to send in a PR? I can help with that if so. If not, no worries. 😄 

(Note that the tooling should stick that in the index once everything else is in place).

**Comment by bat999** [comment]
... would you like to send in a PR? ...

Thanks, but no thanks.
I am not worthy (or capable).
Never have done PRs before.
Better it's left to somebody else I think.
;-)

**Comment by miketaylr** [comment]
OK, no worries -- but, I'm happy to help if you want to learn how. :)
