### ISSUE TITLE
Low-entropy hints should go through permissions policy check

### ISSUE THREAD

**Issue by amtunlimited** [WICG/client-hints-infrastructure#67]
Currently low-entropy hints are added directly to the header list. They should just be added to the client hints set so they can go through the "Should request be allowed to use feature?" algorithm, which is what was originally intended

**Comment by amtunlimited** [comment]
There are two ways we could go about doing this: before or after the client null check (paragraph 3 https://wicg.github.io/client-hints-infrastructure/#request-processing)

Before means that the hints would be added even if there wasn't a client available, which may or may not make sense.

**Comment by amtunlimited** [comment]
@yoavweiss @clelland Any thoughts one way or the other for ⬆️

**Comment by yoavweiss** [comment]
If the client is null, request's window won't be Window, so the permission policy would just always return false.
I think that we'd want the opposite - bypass the check when the client is null (of change the "should request be allowed" algorithm to do what we need when the client is null.

**Comment by amtunlimited** [comment]
https://w3c.github.io/webappsec-permissions-policy/#should-request-be-allowed-to-use-feature

Would step two be equivalent to a null client check?
