### ISSUE TITLE
Consider partitioning Accept-CH cache

### ISSUE THREAD

**Issue by miketaylr** [WICG/client-hints-infrastructure#75]
@johnwilander raises an interesting point in https://github.com/WICG/ua-client-hints/issues/242 (the issue is not specific to UA-CH, hence moving this issue over here).

Should we partition the Accept-CH cache to be consistent with the rest of the storage/network partitioning that's happening elsewhere?

**Comment by davidben** [comment]
The Accept-CH cache is only ever queried for the top-level origin. So as long as the top-level origin is what determines the partition key, partitioning it is a no-op and there wasn't anything cross-site going on anyway.

But describing it as partitioned, despite it being a no-op, seems reasonable to me. We'd avoid having to think about this all the time, and it's more future-proof if partitions end up used in more complex ways.
