### ISSUE TITLE
Standardize existing client hint naming

### ISSUE THREAD

**Issue by arichiv** [WICG/client-hints-infrastructure#76]
Although most newer hints have the new `sec-ch-` prefix, many older ones are missing this. We should ensure standardized naming across all hints to avoid confusion.

**Comment by eeeps** [comment]
When experimenting with the new (`Sec-CH-`) prefixed responsive image client hints, I noticed that Chrome is still sending the old (unprefixed) hints. Is there a timeline on when those will be fully depreciated?

**Comment by arichiv** [comment]
A timeline for deprecation/removal of legacy client hints will be drawn up Q1 2022 (I hope it's completed by Q4 2022, but there are a lot of usage dependent contingencies). Updates can be tracked here: https://bugs.chromium.org/p/chromium/issues/detail?id=1227043
