### ISSUE TITLE
Does empty Accept-CH override the low entropy user-agent hints?

### ISSUE THREAD

**Issue by hamishwillee** [WICG/client-hints-infrastructure#89]
`Accept-CH` from a server indicates the desired client hint headers. The client can then choose (or not) to send back some subset of the requested headers to the server in subsequent requests.

https://web.dev/user-agent-client-hints/ indicates that the set of headers specified in `Accept-CH`  should last for the remainder of the session (until browser closes). I.e. the client effectively caches the request and keeps on attaching the set of requested client hints.
However the server can set a new value of `Accept-CH` to replace the original set.

What is inferred, but I would like to confirm, is that none of this applies to the low entropy hints. My assumption is that a low entropy hint will/should always be sent irrespective of what is specified in `Accept-CH`. So you can't, for example, specify an empty `Accept-CH`  and expect to stop getting `Sec-CH-UA`

I THINK this is covered by "For each client hints token lowEntropyHint in the registry’s low entropy hint table, append lowEntropyHint to hintSet." - i.e. this happens after whatever else comes from Accept-CH.

**Comment by amtunlimited** [comment]
You have it correct, the hints sent to the page are a union of the low-entropy hints set and whatever hints are in the cache, and the header changes the cache.

You can, if you really wanted to, block low-entropy hints from all subresource requests, including the top-level origin, by changing the relevant permission policy, which is something to be careful about if you want to block third-parties or the like.

Feel free to re-open if you have more questions.
