### ISSUE TITLE
Low entropy hint table incorrect prefix for Save-Data?

### ISSUE THREAD

**Issue by hamishwillee** [WICG/client-hints-infrastructure#90]
In the [low entropy hint table](https://wicg.github.io/client-hints-infrastructure/#low-entropy-hint-table) you see the header listed as `Sec-CH-Save-Data`, however if you follow the link the header name is just `Save-Data` (see https://wicg.github.io/savedata/#save-data-request-header-field)

**Comment by arichiv** [comment]
The hint (along with a few others) were renamed a couple months ago to include the sec-ch prefix like the others have. I'll fix the other doc.

Note: sec-ch-save-data launches in M97, and save-data has yet to be deprecated.

**Comment by hamishwillee** [comment]
Ah, thanks @arichiv .  `sec-ch-save-data` and  `save-data` would be treated as separate things with respect to browser compatibility right? That would mean that both would be in the low entropy table too as I understand it.

The spec also seems to indicate that the client -token hint should be lower-cased like `sec-ch-save-data`, but the [glitchme](https://user-agent-client-hints.glitch.me/) seems to indicate the tokens should match the header and I am pretty sure I saw a note that chrome intends to have them match. Is this an error in the spec too or is Chrome doing something odd?

**Comment by arichiv** [comment]
The tokens are handled in a case insensitive manner by chrome, but I believe you're correct about the capitalization when sent in an HTTP request though.

**Comment by yoavweiss** [comment]
One potential problem with updating `save-data` in implementations is that we won't necessarily want to send 2 redundant headers for a long while, and it's hard to gauge usage of `save-data` right now (as it's sent by default).

**Comment by tomayac** [comment]
[User Preference Media Features Client Hints Headers](https://wicg.github.io/user-preference-media-features-headers/) defines [`Sec-CH-Prefers-Reduced-Data`](https://wicg.github.io/user-preference-media-features-headers/#sec-ch-prefers-reduced-data) but [states](https://wicg.github.io/user-preference-media-features-headers/#:~:text=no%2Dpreference%22%20/%20%22reduce%22-,%5Bsavedata%5D%20already%20defines%20a%20Save%2DData%20client%20hint%20header.%20Should%20the%20present%20spec%20then%20define%20Sec%2DCH%2DPrefers%2DReduced%2DData%20for%20consistency%20as%20an%20alias%20of%20Save%2DData%3F,-3.%20Feature%20Registry) that _"[[savedata]](https://wicg.github.io/user-preference-media-features-headers/#biblio-savedata) already defines a Save-Data client hint header"_ and asks whether _"the present spec then [should] define `Sec-CH-Prefers-Reduced-Data` for consistency as an alias of `Save-Data`"_? What's your take on this? For orientation, Chrome so far has just implemented [`Sec-CH-Prefers-Color-Scheme`](https://wicg.github.io/user-preference-media-features-headers/#sec-ch-prefers-color-scheme) from the spec.

**Comment by hamishwillee** [comment]
@yoavweiss I'm interested on your take on https://github.com/WICG/client-hints-infrastructure/issues/90#issuecomment-979758562

**Comment by yoavweiss** [comment]
I'm not sure I see a huge semantic difference between save-data and prefers-reduced-data, so it makes sense to coalesce them. If that's the conclusion, I don't think we need 2 different hints though, and definitely don't want to send multiple identical hints by default, as low-entropy hints.
