### ISSUE TITLE
Document behavior for empty/falsy low-entropy hints.

### ISSUE THREAD

**Issue by mikewest** [WICG/client-hints-infrastructure#99]
To reduce header bloat, the approach of not sending headers by default whose value is `?0` seems reasonable. Fetch Metadata's [`Sec-Fetch-User` header](https://www.w3.org/TR/fetch-metadata/#abstract-opdef-set-user) is a good example of this.

This might be a good rule to agree upon, and document both here in the infrastructure doc, and in the implementation of each low-entropy hint which might have a falsy value.

**Comment by miketaylr** [comment]
This sounds reasonable, assuming sites aren't currently relying on using `Sec-CH-UA-Mobile: ?0` (I can't think of a great reason to do so, but it wouldn't surprise me 🤷 ). 

But spec-wise, it sounds like a good thing to encode now and we can treat changing the behavior difference of "Mobile" in Chromium as a separate concern.

**Comment by arichiv** [comment]
Agreed, I'll have a PR today and start on an intent in chrome for Sec-CH-UA/Sec-CH-UA-Mobile/Sec-CH-UA-Platform.

Since Sec-CH-Save-Data is already in process I can just update the design doc and reply to the intent thread.

**Comment by abeyad** [comment]
This seems to contradict the recent work by @amtunlimited to always send values for all low entropy headers, even if the UA string is overridden (https://chromium-review.googlesource.com/c/chromium/src/+/3484996)

**Comment by eeeps** [comment]
This will make differentiating non-mobile UAs from non-supporting mobile UAs more difficult. Not impossible, but you start to bake in some assumptions...

**Comment by arichiv** [comment]
I think it's consistent with the low entropy spirit to apply this to the entire low entropy client hint set in the standard..

That said, I don't think it's urgent we adopt this in Chrome (except for Save-Data, which already does this). I just want to prevent building a subset of low entropy client hints (ultra low entropy client hints?) that behave different into the standard.

I know there's already a lot of churn, so while we might want to encourage new adoptees to do the logic as @eeeps suggests, I'm not proposing a milestone in the next 6 when we would stop sending it the way we are now.

**Comment by miketaylr** [comment]
> > assuming sites aren't currently relying on using `Sec-CH-UA-Mobile: ?0`
> This will make differentiating non-mobile UAs from non-supporting mobile UAs more difficult.

Yeah, I want to be very careful about changing the default UA client hints behavior. Stability is pretty important, IMHO. Maybe the answer is to just override the behavior described here in the UA-CH spec 🤔 . Will think about it some more.

**Comment by arichiv** [comment]
Changing approach, we'll just override the behavior for Save-Data (and keep the original name): https://github.com/WICG/client-hints-infrastructure/pull/101
